---
title: "PSTAT 131 HW 2"
author: "Ezra Torio"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(tidyverse)
library(tidymodels)
library(corrplot)
library(ggthemes)
tidymodels_prefer()
```

```{r}
getwd()
data <- read_csv("~/Desktop/abalone.csv")
head(data)
```

## Question 1

```{r}
newData <- data
newData$age <- data$rings + 1.5
hist(newData$age, xlab = "Age", main = "Age Distribution of Abalones")
```

The abalone ages are normally distributed and right skewed. Most abalones fall between 7 and 15 years old. It is very rare to find an abalone older than 20.

## Question 2

```{r}
set.seed(823)

abalone_split <- initial_split(newData, prop = 0.80, strata = age)
abalone_train <- training(abalone_split)
abalone_test <- testing(abalone_split)
```

## Question 3

We should not use rings to predict age because age is just (rings +1.5) meaning that they would be perfectly correlated.

```{r}
abalone_recipe <- recipe(age ~ ., data = abalone_train) %>%
 step_rm(rings) %>%
  step_dummy(all_nominal_predictors()) %>%
   step_interact(~ starts_with("type"):shucked_weight) %>%
    step_interact(~ longest_shell:diameter) %>%
     step_interact(~ shucked_weight:shell_weight) %>%
      step_normalize(all_predictors())

abalone_recipe
  
```

## Question 4

```{r}
lm_model <- linear_reg() %>%
  set_engine("lm")
```

## Question 5
```{r}
lm_wflow <- workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(abalone_recipe)

lm_fit <- fit(lm_wflow, abalone_train)
```

## Question 6
```{r}
testAbalone <- tibble(type = "F", longest_shell = 0.50, diameter = 0.10, height = 0.30,
                   whole_weight = 4, shucked_weight = 1, viscera_weight = 2, 
                   shell_weight = 1, rings = 0)

predict(lm_fit, new_data = testAbalone)
```
Predicted age: 23.22974

## Question 7

```{r}
abalone_train_res <- predict(lm_fit, new_data = abalone_train %>% select(-age))
abalone_train_res %>% 
  head()

abalone_train_res <- bind_cols(abalone_train_res, abalone_train %>% select(age))
abalone_train_res %>% 
  head()

rmse(abalone_train_res, truth = age, estimate = .pred)

abalone_metrics <- metric_set(rmse, rsq, mae)
abalone_metrics(abalone_train_res, truth = age, 
                estimate = .pred)
```







